### ISSUE TITLE
Video playing issue

### ISSUE THREAD

**Issue by ameenmaheen** [FinweLtd/orion360-sdk-basic-hello-android#2]
Hi guys

I am using the basic sdk, i have noticed that we are having a problem when playing the video like the audio only played and the video still buffering , The issue noted in android N when played samsung s6 which runs on marshmellow it works fine , why this happening ? how can it be solved

**Comment by ameenmaheen** [comment]
I could see that the onPrepared callback started the play back but mOrionVideoView.getCurrentPosition() giving 0 always even when the sound is playing

**Comment by trantako** [comment]
Hi,

Can you please post more information about the issue, such as:
- What is the test device make & model that produces the issue?
- What is your test video resolution? Maybe you can share a sample video download link to support@finwe.fi?
- Do you experience the issue with our sample code or with your own code?

Typically audio-only playback means either that video resolution is too high for the device, unsupported video format, or invalid license file.

**Comment by ameenmaheen** [comment]
Hi @trantako 
1. I've tested the video in samsung s6 and works fine ,when played on moto g4 plus only audio only played video not playing
2. This is the video url
[https://s3.amazonaws.com/360degreemea/Jordan360Videos/Jordan+360+Warfare+mobile.mp4](url)
3.I have no issue when playing your sample video url , so i am guessing problem is with video resolution .

**Comment by trantako** [comment]
Thank you for sending the test video. It is indeed a 4k video, so likely does not play on Moto G4 Plus. FullHD videos should play fine on this device.

**Comment by ameenmaheen** [comment]
Same issue happened in Asus zenfone , I couldn't find any video properties when opened  my video with vlc player , when i opened  your test video in vlc player  there was video properties information , like 32 frames like that kind of information , may be my video is not compatible with your sdk requirement, have you checked the video ?  may be samsung s6 overcoming that compatibility issue somehow ..  because the Samsung galaxy S3 couldn't open it either ..

**Comment by trantako** [comment]
The key thing here is whether a particular device's hardware video decoder can extract frames from the video file, or not. In general there are two popular "quality levels", FullHD capable video decoders and 4k capable video decoders and it depends on the chipset that is being used in a particular device.

Orion360 SDK (Basic) for Android uses the media player APIs for decoding video. This means that all videos that can be played back with the device's native video player should work also with Orion360, and those that do not play back with it will also fail with Orion360.

Your sample video was 4k, so all devices that support only up to FullHD resolution will fail to play that file. The solution is to offer two qualities for users so they can choose lower quality if their device cannot handle the best quality. The Pro version of the SDK also supports HLS streams where this selection is automatic.

**Comment by ameenmaheen** [comment]
@trantako thank you for the helpful information
