### ISSUE TITLE
Zoom out to the maximum for the videos

### ISSUE THREAD

**Issue by sajansaha55** [FinweLtd/orion360-sdk-basic-hello-android#5]
Can we have the zoom out to the maximum for the videos as currently its zoomed in a lot which quality shows as not great. I am trying to have the default zoom as zoomed out to the maximum.  With iOS we could do it by setting "initialFov" property. Please help.

**Comment by trantako** [comment]
With Orion360 SDK Basic for Android, you can adjust FOV as follows:

```
OrionViewConfig cfg = mOrionVideoView.getCurrentConfigCopy();
cfg.setFov(
    90,   // Initial value
    60,   // Minimum value
    120  // Maximum value
);
try {
    mOrionVideoView.applyConfig(cfg);
} catch (OrionViewConfig.NotSupportedException e) {
    Log.e(TAG, "Selected configuration is not supported!");
}
```
