### ISSUE TITLE
Videos are not working on Samsung galaxy S8 and S8 plus

### ISSUE THREAD

**Issue by sajansaha55** [FinweLtd/orion360-sdk-basic-hello-android#6]
The buffering circle and video is working only if we touches the player. Once you release finger from player, the video pauses. This issue exists only on S8 and S8plus.  We have tested the sample orion app and the issue exists on that as well. Please check it and provide a solution asap.

Please check the attached video for more information.

[s8 orion.zip](https://github.com/FinweLtd/orion360-sdk-basic-hello-android/files/1418464/s8.orion.zip)

**Comment by trantako** [comment]
Confirmed. This has been fixed in version 1.2.07.

**Comment by sajansaha55** [comment]
@trantako Thanks Tapani... Its working now.
